[admin:SA_haveibeenpwned]
match = /
members = SA_haveibeenpwned_settings

[admin_external:SA_haveibeenpwned_settings]
handlertype = python
handlerfile = SA_haveibeenpwned_rh_settings.py
handleractions  = edit, list
python.required = python3.13,python3.9
python.version = python3.9
